server:
  port: 8001
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ayuee/cloud-git/    # 配置git仓库的地址
          search-paths: config-repo                             # git仓库地址下的相对地址，可以配置多个，用,分割。
          username:                                              # git仓库的账号
          password:
    bus:
      trace:
        enabled: true                                                     # git仓库的密码
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

#management:
#  endpoints:
#    web:
#      exposure:
#        include: bus-refresh

management:
  security:
     enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/   ## 注册中心eurka地址

